const language = {
    title: { fin: 'Tervetuloa käyttämään opiskelijakuntien yhteistä edustajistovaalien vaalikonetta!', eng: 'Welcome to use the student unions’ Voting Aid!', swe: 'Välkommen att använda studerandekårernas gemensamma valkompass!' },
    registrationTitle: { fin: 'Rekisteröidy', eng: 'Register', swe: 'Registrering' },
	loginTitle: { fin: 'Kirjaudu sisään', eng: 'Login', swe: 'Logga in' },
	homePageDescription: { fin: 'Aloita valitsemalla valikosta oman korkeakoulusi opiskelijakunta ja löydä sinulle parhaiten sopiva ehdokas edustajistovaaleissa.', eng: 'Start by choosing your own student union in the menu, and find the best candidate for you to vote for in the Representatives Council Election.', swe: 'Börja med att välja din studerandekår i drop-down menyn och hitta den bästa kandidaten för just dig i detta val. ' },
    registrationPageDescription: { fin: 'Hei ehdokas! Luo tunnus samalla sähköpostilla, johon sait rekisteröitymisohjeet.', eng: 'Hello candidate! Create an account using the same email in which you received the instructions.', swe: 'Hej kandidat! Skapa ett konto med samma e-post som du fick registreringsinstruktionerna till ' },
	loginPageDescription: { fin: 'Tämä sivu on tarkoitettu ainoastaan edustajistovaalien ehdokkaille. Kirjauduthan sisään aiemmin rekisteröimilläsi tunnuksilla.', eng: 'This page is for the candidates only. Log in using the information you have registered with.', swe: 'Denna sida är endast för kandidater i fullmäktigevalet. Logga in med de inloggningsuppgifter som du registrerade tidigare. ' },
	selectStudentAssociation: { fin: 'Valitse opiskelijakuntasi', eng: 'Choose your student union', swe: 'Välj din studerandekår' },
    navigationHome: { fin: 'Koti', eng: 'Home', swe: 'Hem' },
    navigationLogin: { fin: 'Kirjaudu sisään', eng: 'Login', swe: 'Inloggning' },
    navigationRegister: { fin: 'Rekisteröidy', eng: 'Register', swe: ' Registrering' },
    navigationLogOut: { fin: 'Kirjaudu ulos', eng: 'Logout', swe: 'Logga ut' },
    navigationProfile: { fin: 'Profiili', eng: 'Profile', swe: ' Profil' },
    formButton: { fin: 'Vastaa vaalikoneeseen', eng: 'Answer the Voting Aid questions', swe: 'Fyll i valkompassen' },
    loginButton: { fin: 'Kirjaudu', eng: 'Login', swe: 'Logga in' },
    loginHolder: { fin: 'Olet onnistuneesti kirjautunut sisään!', eng: 'You have succesfully logged in', swe: 'Inloggningen lyckades' },
    mainPageLink: { fin: 'Takaisin etusivulle', eng: 'Back to main page', swe: 'Tillbaka till framsidan' },
    registerButton: { fin: 'Rekisteröidy', eng: 'Register', swe: 'Registrering' },
    emailPlaceHolder: { fin: 'Sähköpostiosoite', eng: 'Email', swe: 'E-postadress' },
    passwordPlaceHolder: { fin: 'Salasana', eng: 'Password', swe: ' Lösenord' },
    passwordConfirmationPlaceHolder: { fin: 'Salasanan varmennus', eng: 'Password confirmation', swe: ' Lösenordsverifiering' },
    // missing swedish----------
    registrationError: { fin: 'Et voi rekisteröityä sellaisella sähköpostiosoitteella, jota ei ole lisätty tietokantaan kandidaattina!', eng: 'You cannot register an account for email address that does not exist as a candidate!' },
    passwordConfirmationError: { fin: 'Varmennetun salasanan täytyy täsmätä salasanan kanssa', eng: 'Confirmation password must match with password' },
    profileButton: { fin: 'Varmista tiedot', eng: 'Submit Information' },
    adminLogo: { fin: 'Ylläpitäjän paneli', eng: 'Admin Panel' },
    addCandidatesCautionHolder: { fin: 'Lisätään kandidaatit, jotka eivät ole tietokannassa', eng: 'This will add all the candidates, which are not present in the database' },
    fillFormButton: { fin: 'Lähetä', eng: 'Submit', swe: 'Skicka' },
    continueHolder: { fin: 'Jatka', eng: 'Proceed' },
    browseButton: { fin: 'Selaa', eng: 'Browse file' },
    // filterCandidateLabel: { fin: 'Suodata koulun perusteella', eng: 'Filter by School' },
    uploadPicture: { fin: 'Lataa profiilikuva', eng: 'Upload a profile picture' },
    candidateHolder: { fin: 'Kandidaatti', eng: 'Candidate' },
    successQuestionAddedHolder: { fin: 'Olet onnistuneesti lisännyt uuden kysymyksen', eng: 'You have succesfully submitted a question"' },
    wrongPasswordHolder: { fin: 'Väärä käyttäjätunnus tai salasana', eng: 'Invalid Username Or Password' },
    addedCandidatesToDatabaseAlert: { fin: 'Kanditaatit onnistuneesti lisätty tietokantaan', eng: 'Candidates have been added into the database' },
    addingOneCandidateToDatabaseAlert: { fin: 'Kandidaatti onnistuneesti lisätty tietokantaan', eng: 'Succesfully added user to database' },
    addingOneCandidateToDatabaseErrorAlert: { fin: 'Kandidaatti tällä sähköpostiosoitteella on jo olemassa', eng: 'Email with this address already exists as a user' },
    changeProfileDataAlert: { fin: 'Olet onnistuneesti päivittänyt profiilisi tiedot', eng: 'You have Succesfully updated your profile data' },
    filledFormAlert: { fin: 'Olet onnistuneesti täyttänyt kyselyn', eng: 'You have succesfully filled the form' },
    // -----------
    oneCandidate: { fin: 'Täytä alla olevat tiedot lisätäksesi yhden kandidaatin:', eng: 'Fill in the information below to add one candidate:', swe: 'Fyll i informationen nedan för att lägga till en kandidat' },
    manyCandidates: { fin: 'Voit lisätä useamman kandidaatin alla olevan linkin kautta. Vain CSV tiedostot käyvät. ', eng: 'You can add candidates by the link below. Only CSV files are acceptable.', swe: ' Du kan lägga till fler kandidater via länken nedan. Endast CSV -filer fungerar' },
    addCandidates: { fin: 'Lisää monta kandidaattia', eng: 'Add Candidates', swe: 'Lägg till flera kandidater' },
    addCandidate: { fin: 'Lisää yksi kandidaatti', eng: 'Add One Candidate', swe: 'Lägg till en kandidat' },
    browseCandidates: { fin: 'Selaa kandidaatteja', eng: 'Browse Candidates', swe: 'Bläddra kandidater' },
    addQuestion: { fin: 'Lisää kysymys', eng: 'Add Question', swe: 'Lägg till en fråga' },
    browseQuestions: { fin: 'Selaa kysymyksiä', eng: 'Browse Questions', swe: 'Bläddra frågor' },
    removeButton: { fin: 'Poista', eng: 'Remove', swe: 'Ta bort' },
    agreeButton: { fin: 'Samaa mieltä', eng: 'Agree', swe: 'Samma åsikt' },
    disagreeButton: { fin: 'Eri mieltä', eng: 'Disagree', swe: 'Annan åsikt' },
    matchingCandidates: { fin: 'Saman näkemyksen omaavat kandit:', eng: 'Candidates with matching values:', swe: ' Kandidater med liknande åsikt' },
    firstName: { fin: 'Etunimi:', eng: 'First name:', swe: 'Förnamn' },
    surName: { fin: 'Sukunimi:', eng: 'Surname:', swe: 'Efternamn' },
    school: { fin: 'Koulu:', eng: 'School:', swe: ' Högskola:' },
    selectStudentAssociationList: { fin: 'Opiskelijakunta:', eng: 'Student Association:', swe: 'Studerandekår:' },
    campus: { fin: 'Kampus:', eng: 'Campus:', swe: 'Campus' },
    electoralDistrict: { fin: 'Vaalipiiri:', eng: 'Electoral District:', swe: 'Valcirkel:' },
    electoralAlliance: { fin: 'Vaaliliitto:', eng: 'Electoral Alliance:', swe: 'Valförbund:' },
    description: { fin: 'Kuvaus:', eng: 'Description:', swe: ' Beskrivning:' },
    addQuestionButton: { fin: 'Lisää kysymys', eng: 'Add question' },
    deleteButton: { fin: 'Poista', eng: 'Delete', swe: 'Ta bort' },
    editButton: { fin: 'Muokkaa', eng: 'Edit', swe: ' Redigera' },
    updateButton: { fin: 'Päivitä tiedot', eng: 'Update your information', swe: 'Uppdatera information' },
    formLink: { fin: 'Linkki täytettyyn kyselyyn', eng: 'Link to your filled form', swe: 'Länk till ditt ifyllda formulär' },
    studentAssociationHolder: { fin: 'Opiskelijakunta', eng: 'Student Association', swe: 'Studerandekår' },
    deleteHolder: { fin: 'Poista', eng: 'Delete', swe: 'Ta bort' },
    questionHolder: { fin: 'Kysymys:', eng: 'Question:', swe: ' Fråga:' },
    noSimilarCandidates: { fin: 'Valitettavasti kukaan ei ollut samaa mieltä kanssasi', eng: 'Unfortunately no one related with your answers', swe: ' Tyvärr var det ingen som var av samma åsikt som dig' },
}

export default language;